/* SPDX-License-Identifier: BSD-2-Clause */
#ifndef CONFIDENTIAL_IOT_TA_H
#define CONFIDENTIAL_IOT_TA_H

#define TA_CONFIDENTIAL_IOT_UUID \
	{ 0x7d9f6d20, 0x5f11, 0x4d0c, \
		{ 0x9a, 0x17, 0x61, 0xc9, 0xc9, 0x1c, 0x00, 0x01 } }

#define TA_CONFIDENTIAL_IOT_CMD_AUTHENTICATE_SENSOR		0
#define TA_CONFIDENTIAL_IOT_CMD_PROCESS_SENSOR_DATA		1
#define TA_CONFIDENTIAL_IOT_CMD_PROTECT_SENSOR_DATA		2
#define TA_CONFIDENTIAL_IOT_CMD_GENERATE_ATTESTATION_EVIDENCE	3

#endif /* CONFIDENTIAL_IOT_TA_H */
